name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0

    - uses: docker/build-push-action@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mrdrache333/java-studip-telegram-bot:$(date +%s)
